// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using blog_template_practice;

namespace BlogPlatform.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20201021210826_FirstSeedDataAddition")]
    partial class FirstSeedDataAddition
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("blog_template_practice.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "MMO"
                        },
                        new
                        {
                            Id = 2,
                            Name = "RPG"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Shooter"
                        });
                });

            modelBuilder.Entity("blog_template_practice.Models.Content", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("PublishDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Contents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Leeroy Jenkins",
                            Body = "One of the most prominent MMOs out there, you’d think there’s more memes than players at this point. If you don’t have a life, or a significant other… Welcome home. If you have either of those things, when you pick up this game, buy them something nice to compensate for your soon-to-be missing presence.",
                            CategoryId = 1,
                            PublishDate = "10/21/2020",
                            Title = "World of Warcraft"
                        },
                        new
                        {
                            Id = 2,
                            Author = "ILeftMyStoveOn",
                            Body = "Do you like crafting? Do you like running around, cutting down trees, heaving a metal object at rocks for hours at end? Well… you’ll like this. Sure you can fight things, but why do that when you can literally live your best life in this game?",
                            CategoryId = 1,
                            PublishDate = "10/21/2020",
                            Title = "New World"
                        },
                        new
                        {
                            Id = 3,
                            Author = "HanShotFirst",
                            Body = "Oldie but goldie. Do you want to be a Sith, frying your boss with lightning to get a promotion? We got you. Do you want to be a Jedi who makes mildly amusing comments to your enemies? We got you. You’ve got a ship, a galaxy to explore and crewmates to romance. No excuses.",
                            CategoryId = 1,
                            PublishDate = "10/21/2020",
                            Title = "Star Wars: The Old Republic"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Order 66",
                            Body = "I expected this to be terrible in typical EA fashion. It turned out to be one of the best Star Wars games in recent memory. Congratulations. If they had given us less ponchos and more sith magic, it’d be a 10/10.",
                            CategoryId = 2,
                            PublishDate = "10/21/2020",
                            Title = "Jedi: Fallen Order"
                        },
                        new
                        {
                            Id = 5,
                            Author = "DudeSomeoneStoleMySweetRoll",
                            Body = "Do I even need to say anything? I Fus Ro Dah’d my horse off a cliff. Top that.",
                            CategoryId = 2,
                            PublishDate = "10/21/2020",
                            Title = "Skyrim"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Boy",
                            Body = "Most commonly referred to as ‘Disappointed Father Simulator 2018’. Also, there’s a giant talking snake that is friendly.",
                            CategoryId = 2,
                            PublishDate = "10/21/2020",
                            Title = "God of War"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Activision",
                            Body = "I don’t even have time to explain why I don’t have time to explain. That’s it. Go away.",
                            CategoryId = 3,
                            PublishDate = "10/21/2020",
                            Title = "Destiny 2"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Don’t Get Cocky, Kid",
                            Body = "You get to live out your fantasies of flying Star Wars ships, killing opposing faction pilots. You get to have a cute little dangly mini Ewok in your cockpit.",
                            CategoryId = 3,
                            PublishDate = "10/21/2020",
                            Title = "Star Wars: Squadrons"
                        },
                        new
                        {
                            Id = 9,
                            Author = "ReviveMePls",
                            Body = "Lack of originality meets tons of Activision money. They made something that has few original ideas, but has enough polish to put other games to shame. Good job, I guess?",
                            CategoryId = 3,
                            PublishDate = "10/21/2020",
                            Title = "Warzone"
                        });
                });

            modelBuilder.Entity("blog_template_practice.Models.Content", b =>
                {
                    b.HasOne("blog_template_practice.Models.Category", "Category")
                        .WithMany("Contents")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
